"""Added is_available field to all category tables

Revision ID: 5d6fb92cdc14
Revises: 043fd7b6b959
Create Date: 2023-12-22 23:45:18.373979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6fb92cdc14'
down_revision = '043fd7b6b959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appliances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))

    with op.batch_alter_table('furniture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))

    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))

    with op.batch_alter_table('stationery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stationery', schema=None) as batch_op:
        batch_op.drop_column('is_available')

    with op.batch_alter_table('shoes', schema=None) as batch_op:
        batch_op.drop_column('is_available')

    with op.batch_alter_table('furniture', schema=None) as batch_op:
        batch_op.drop_column('is_available')

    with op.batch_alter_table('appliances', schema=None) as batch_op:
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###
